version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nastya
      POSTGRES_PASSWORD: pgspgs
      POSTGRES_DB: books
    ports:
      - "5455:5455"
    command: -p 5455
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Путь к SQL скрипту
  books-checker:
    build: .
    depends_on:
      db:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://nastya:pgspgs@db:5455/books?sslmode=disable
    restart: on-failure